### ISSUE TITLE
Validatable required

### ISSUE THREAD

**Issue by lbadura** [ThoughtWorksStudios/oauth2_provider#2]
I didn't see anywhere in the docs that validatable is required. Perhaps that information could be added to the readme.

**Comment by ketan** [comment]
Hey, thanks for bringing this up. We missed out on documenting this as part of the readme... will look into this ASAP.

Thanks!

-- Ketan

**Comment by lbadura** [comment]
No problem. Thanks for all of the good work on the plugin !
