### ISSUE TITLE
User Model

### ISSUE THREAD

**Issue by jridgway** [ThoughtWorksStudios/oauth2_provider#4]
Is it possible to use this gem with a user model named "Member" rather than "User." I see "current_member" used frequently, which will conflict with my app. I have multiple logins, one for admins and one for members. Any tips would be greatly appreciated. Thanks!

**Comment by djrice** [comment]
Hi - This plugin does not depend upon the presence of an ActiveRecord model named 'User.'  In fact you can even use it with a non-AR data source. The interface between the systems, a string identifying the user, while called 'user_id' by the plugin, is not tied to any particular model.  Your login mechanism will need to lookup the model instance via that string, e.g., Member.find(user).  Short story, should work great if you have a user model named "Member."
