### ISSUE TITLE
Any plan for User Agent profile?

### ISSUE THREAD

**Issue by olance** [ThoughtWorksStudios/oauth2_provider#5]
Hi!

Your plugin looks like the most promising I've found to act as a OAuth2 provider, thanks for the excellent work! :)
I was wondering if you had any plan on adding support for the User Agent profile?

Thanks!

**Comment by djrice** [comment]
Hi - Unfortunately, we don't have plans in the near future to support different profiles or flows.

**Comment by olance** [comment]
Hi,

thanks for your reply!
I'll try implementing it then... ^^
