### ISSUE TITLE
Error in Readme - Initializer sample

### ISSUE THREAD

**Issue by olance** [ThoughtWorksStudios/oauth2_provider#6]
The initializer sample's last instruction is:
    # use host app's custom authorization filter to protect admin actions on OauthUserTokensController
    OauthClientsController.before_filter(:ensure_admin_user, :only => [:revoke_by_admin])

I guess this is what it's supposed to be:
    # use host app's custom authorization filter to protect admin actions on OauthUserTokensController
    OauthUserTokensController.before_filter(:ensure_admin_user, :only => [:revoke_by_admin])

No big deal but it can't be wrong fixing it ^^

**Comment by wpc** [comment]
fixed, thank you very much @olance

**Comment by olance** [comment]
You're welcome :)
