### ISSUE TITLE
Gem dependency problem - Rails 3 / Bundler support?

### ISSUE THREAD

**Issue by celeduc** [ThoughtWorksStudios/oauth2_provider#7]
I'm running into some dependency issues while using Bundler 1.0.10 and Ruby 1.8.7 in a Rails 3.0.3 project:

First off, Bundler can't detect the dependency that oauth2_provider has on Validatable.  If you add that to the Gemfile, you then run into this issue:

```
/usr/lib/ruby/gems/1.8/gems/oauth2_provider-0.2.0/lib/oauth2/provider/model_base.rb:13: uninitialized constant Oauth2::Provider::ModelBase::Validatable (NameError)
```

You can get past this by adding "require 'validatable'" to the top of that file, but then you run into the next issue:

```
/usr/lib/ruby/gems/1.8/gems/oauth2_provider-0.2.0/app/controllers/oauth2/provider/oauth_authorize_controller.rb:6: uninitialized constant ApplicationController (NameError)
```

... and so on.

**Comment by dkrusenstrahle** [comment]
Same problem. Please help!

**Comment by celeduc** [comment]
Well, I've fixed the first part of this by adding <code>require 'validatable'</code> on the line _before_ <code>require 'oauth2_provider'</code> in the Gemfile.  But I'm still running into the ApplicationController issue.

**Comment by celeduc** [comment]
I've validated this on a clean machine with Rails 3.0.3. Steps to reproduce this issue:

<pre><code>$ rails new test_app
$ cd test_app
# add the following new lines to Gemfile after rails:
  require 'validatable'
  require 'oauth2_provider'
$ bundle install
$ rake test
(in /src/test_app)
********************************************************************************
*** Using data source: Oauth2::Provider::ARDatasource
********************************************************************************
rake aborted!
uninitialized constant Oauth2::Provider::ApplicationController
/src/test_app/Rakefile:4
(See full trace by running task with --trace)
</code></pre>

**Comment by celeduc** [comment]
*\* workaround **
Put this in your config/application.rb, just after "require 'rails/all'" (and _before_ bundler):
<code><pre>class ApplicationController < ActionController::Base
end</pre></code>
That will at least get you past this dependency issue, at least so that Rake will run again.

**Comment by dkrusenstrahle** [comment]
Still problem, should the above class be empty?

**Comment by celeduc** [comment]
This needs more work for Rails 3, and is beyond my abilities.

**Comment by djrice** [comment]
Hey Guys - Sorry about this. You are correct if you're thinking that we're using this for Rails 2.3.x and not 3.0.x.  We will try to take a look at this as soon as possible.  Wish I had a better answer for you.

**Comment by dkrusenstrahle** [comment]
It would be great if we could get it to work with Rails 3. I looks like a very good gem!
In the mean time, do you know of any gem, compatible with Rails 3, that I can use to create a oAuth provider?

**Comment by dkrusenstrahle** [comment]
It would be great if we could get it to work with Rails 3. I looks like a very good gem!
In the mean time, do you know of any gem, compatible with Rails 3, that I can use to create a oAuth provider?

**Comment by celeduc** [comment]
@dkrusenstrahle I haven't seen any.

**Comment by rubyconvict** [comment]
I had a similar problem with some other gem, your *\* workaround *\* is cool, thanks!
